# Generated by Django 3.0.3 on 2020-03-11 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='picture_src',
            field=models.URLField(blank=True, null=True),
        ),
    ]
