# Generated by Django 3.0.3 on 2020-03-11 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('headline', models.CharField(max_length=150)),
                ('byline', models.TextField(null=True)),
                ('author', models.CharField(max_length=150)),
                ('date_published', models.DateTimeField(auto_now_add=True)),
                ('num_sections', models.IntegerField()),
                ('picture_src', models.URLField()),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
            },
        ),
    ]
