# Generated by Django 3.0.3 on 2020-03-11 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20200312_0322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='byline',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='num_sections',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
