# Generated by Django 3.0.3 on 2020-03-11 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20200312_0337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='picture_src',
            field=models.URLField(blank=True, null=True),
        ),
    ]
