LINKEDIN_LOGIN_URL = 0
LINKEDIN_LOGIN_LOGO = 0
LINKEDIN_REDIRECT_URL = 0
LINKEDIN_TOKEN_URL = 0
LINKEDIN_GET_EMAIL_URL = 0
LINKEDIN_GET_NAME_URL = 0

FACEBOOK_LOGIN_URL = 0
FACEBOOK_LOGIN_LOGO = 0
FACEBOOK_REDIRECT_URL = 0
FACEBOOK_TOKEN_URL = 0

PERSPECTIVE_API_URL = 0
