# Generated by Django 3.0.3 on 2020-03-11 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('num_votes', models.IntegerField()),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('section', models.IntegerField()),
                ('comment_type', models.CharField(choices=[('E', 'Expert'), ('U', 'User')], max_length=1)),
                ('article_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='articles.Article')),
                ('creator_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='users.User')),
                ('parent_comment_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children_comments', to='comments.Comment')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
            },
        ),
    ]
