# Generated by Django 3.0.3 on 2020-03-22 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('sections', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('num_votes', models.IntegerField(blank=True, default=0)),
                ('num_shares', models.IntegerField(blank=True, default=0)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField()),
                ('comment_type', models.CharField(choices=[('E', 'Expert'), ('U', 'User')], max_length=1)),
                ('article_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='sections.Section')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='users.User')),
                ('parent_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='comments.Comment')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments',
            },
        ),
    ]
