# Generated by Django 3.0.3 on 2020-03-11 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0002_auto_20200312_0337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='num_votes',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
