# Generated by Django 3.0.3 on 2020-03-19 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0004_auto_20200312_0351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_type',
            field=models.CharField(blank=True, choices=[('E', 'Expert'), ('U', 'User')], default='U', max_length=1),
        ),
    ]
